---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: app
  name: app
  namespace: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      containers:
      - name: app
        image: surajnarwade/test-app:latest
        resources:
          requests:
            cpu: 3m
        ports:
        - name: web
          containerPort: 8080
