---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-app-dev
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        owner: surajincloud
        repo: test-app-code # This is the application source code repo
        # tokenRef:
        #   secretName: github-token
        #   key: token
        labels:
        - deploy # label on PR that trigger review app
  template:
    metadata:
      name: 'test-app-dev-{{branch}}-{{number}}'
    spec:
      source:
        repoURL: git@github.com:surajincloud/test-app-infra.git
        targetRevision: main
        path: envs/dev
        helm:
          parameters:
          - name: "image.tag"
            value: "{{branch}}-{{head_sha}}" # override of the image tag
          - name: "ingress.prefix"
            value: "{{branch}}" # add a prefix to the URL 
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: test-app-dev
