apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app-prod
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: test-app-prod
    server: https://kubernetes.default.svc 
  project: default
  source:
    repoURL: https://github.com/surajincloud/test-app-infra
    path: envs/prod
    targetRevision: main
