apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app-stage
  namespace: argocd
spec:
  destination:
    namespace: test-app-stage
    server: https://kubernetes.default.svc 
  project: default
  source:
    repoURL: https://github.com/surajincloud/test-app-helm-chart.git
    path: envs/stage
    targetRevision: main
